[project]
name = "homecoming-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.4.2",
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
]
